# Generated by Django 5.0.6 on 2024-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="ایمیل")),
                (
                    "phone",
                    models.IntegerField(max_length=11, verbose_name="شماره تماس"),
                ),
                ("message", models.TextField(null=True, verbose_name="متن تماس با ما")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("description", models.TextField(verbose_name="پاسخ تماس با ما")),
                (
                    "is_called",
                    models.BooleanField(
                        default=False, verbose_name="تماس گرفته  شده/نشده"
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "لیست تماس با ما",
            },
        ),
    ]
