# Generated by Django 5.0.6 on 2024-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.IntegerField(verbose_name="شماره تماس"),
        ),
    ]
