# Generated by Django 5.0.6 on 2024-06-10 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_module", "0004_alter_contactus_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(13),
                    django.core.validators.RegexValidator(
                        message="شماره تلفن وارد شده معتبر نیست. لطفاً یک شماره تلفن معتبر ایران وارد کنید.",
                        regex="^(?:\\+98|0)?9\\d{9}$",
                    ),
                ],
            ),
        ),
    ]
